### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-css-intro#1]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](http://aware-queen.surge.sh).

**Comment by chrisvfritz** [comment]
Looks great! :shipit: Two things I noticed that could be improved slightly. The first is that [this `display: block`](https://github.com/KatieMFritz/codelab-css-intro/blob/master/style.css#L30) isn't actually doing anything, (`display: block` is the default for `section` and most other elements), so that line can be removed. The other is that you might consider implementing a style like this so that the bottom margin of the last `section` doesn't double up with the bottom padding of the `main`:

``` css
main > section:last-child {
  margin-bottom: 0;
}
```

**Comment by KatieMFritz** [comment]
:+1:
